/* Dark Console / Privacy page: multilingual, plain-language privacy policy for the current static app. */

import { useEffect, useState } from "react";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { getPreferredLanguage, savePreferredLanguage, type SiteLanguage } from "@/lib/i18n";

const CONTACT_EMAIL = "chtasaba@gmail.com";

const policyCopy = {
  ar: { dir: "rtl", header: "سياسة الخصوصية", back: "← رجوع للموقع", eyebrow: "Privacy Policy", title: "سياسة الخصوصية", lead: "هاد السياسة كتشرح شنو كيدير GGUF Finder بالمعلومات ملي كتستعمل الموقع.", note: "هاد الصفحة كتشرح طريقة استعمال المعلومات فالنسخة الحالية من الموقع. ماشي استشارة قانونية؛ راجعها مع مختص إذا كان الموقع غادي يستقبل زوار من دول عندها متطلبات خاصة.", sections: [["1. شنو هو GGUF Finder؟", "GGUF Finder أداة بسيطة كتعاونك تلقى ملفات نماذج GGUF فـHugging Face. الموقع ما كيطلبش منك حساب، password، أو معلومات شخصية باش تستعمل البحث."], ["2. المعلومات اللي كتدخل", "ملي كتلسّق رابط مستودع أو اسم owner، كيتستعمل هاد النص غير باش يطلب معلومات عامة من Hugging Face API. ما كنخزّنش هاد النص فقاعدة بيانات ديالنا، وما كنبيعوش لأي جهة."], ["3. التخزين المؤقت", "الموقع يقدر يستعمل التخزين المؤقت داخل المتصفح باش يعاود يجيب نفس نتائج البحث بسرعة. هاد التخزين مرتبط بالجلسة ديال المتصفح وماشي قاعدة بيانات دائمة عندنا."], ["4. Hugging Face والروابط الخارجية", "نتائج الملفات وروابط التحميل جايين من Hugging Face. ملي كتفتح رابط أو كتبدأ تحميل، كتولي خاضع لسياسة الخصوصية والشروط ديال الموقع الخارجي."], ["5. الإعلانات", "حالياً ما كاين حتى كود إعلانات مركّب فهاد النسخة. إذا زدنا شبكة إعلانات من بعد، غادي نحدّث هاد الصفحة باسم الشبكة، نوع البيانات اللي كتستعملها، واش كتستعمل cookies، وكيفاش تقدر ترفض الإعلانات المخصصة."], ["6. التحليلات والكوكيز", "أي analytics أو cookies إضافية غادي نصرّحو بها هنا قبل تفعيلها. النسخة الحالية كتحتاج فقط وظائف الموقع الأساسية والبحث العام."], ["7. التواصل", `إلى عندك سؤال على الخصوصية، تواصل معنا عبر: ${CONTACT_EMAIL}.`], ["8. تاريخ التحديث", "آخر تحديث: 15 غشت 2026."]] },
  fr: { dir: "ltr", header: "Politique de confidentialité", back: "← Retour au site", eyebrow: "Privacy Policy", title: "Politique de confidentialité", lead: "Cette politique explique comment GGUF Finder traite les informations lorsque vous utilisez le site.", note: "Cette page décrit le traitement des informations dans la version actuelle du site. Ce n’est pas un avis juridique ; faites-la examiner si vous ciblez des pays ayant des exigences particulières.", sections: [["1. Qu’est-ce que GGUF Finder ?", "GGUF Finder est un outil simple pour trouver des fichiers de modèles GGUF sur Hugging Face. Le site ne demande ni compte, ni mot de passe, ni information personnelle pour effectuer une recherche."], ["2. Informations saisies", "Le lien de dépôt ou le nom d’utilisateur que vous saisissez sert uniquement à demander des informations publiques à l’API Hugging Face. Nous ne le stockons pas dans une base de données et ne le vendons pas."], ["3. Cache", "Le site peut utiliser un cache temporaire du navigateur pour afficher à nouveau des résultats plus rapidement. Ce cache est lié à la session du navigateur, pas à notre base de données."], ["4. Hugging Face et liens externes", "Les résultats et les liens de téléchargement proviennent de Hugging Face. Lorsque vous ouvrez un lien ou téléchargez un fichier, les politiques du site externe s’appliquent."], ["5. Publicité", "Aucun code publicitaire n’est installé dans cette version. Si un réseau publicitaire est ajouté, cette page précisera son nom, ses données, ses cookies éventuels et le moyen de refuser la personnalisation."], ["6. Analytique et cookies", "Tout outil d’analytique ou cookie supplémentaire sera déclaré ici avant son activation. La version actuelle utilise seulement les fonctions essentielles et la recherche publique."], ["7. Contact", `Pour toute question de confidentialité, contactez : ${CONTACT_EMAIL}.`], ["8. Mise à jour", "Dernière mise à jour : 15 août 2026."]] },
  en: { dir: "ltr", header: "Privacy Policy", back: "← Back to site", eyebrow: "Privacy Policy", title: "Privacy Policy", lead: "This policy explains how GGUF Finder handles information when you use the site.", note: "This page describes information handling in the current version of the site. It is not legal advice; have it reviewed if you target jurisdictions with specific requirements.", sections: [["1. What is GGUF Finder?", "GGUF Finder is a simple tool for finding GGUF model files on Hugging Face. The site does not require an account, password, or personal information to search."], ["2. Information you enter", "A repository link or owner name is used only to request public information from the Hugging Face API. We do not store it in a database or sell it to anyone."], ["3. Cache", "The site may use temporary browser cache to show the same search results more quickly. This cache is tied to the browser session, not a permanent database controlled by us."], ["4. Hugging Face and external links", "Results and download links come from Hugging Face. When you open a link or download a file, that external site’s terms and privacy policy apply."], ["5. Advertising", "No advertising code is installed in this version. If an ad network is added, this page will name it, explain its data and cookies, and state how personalised ads can be refused."], ["6. Analytics and cookies", "Any additional analytics or cookies will be disclosed here before activation. The current version only uses essential site functions and public search."], ["7. Contact", `For privacy questions, contact: ${CONTACT_EMAIL}.`], ["8. Updated date", "Last updated: August 15, 2026."]] },
} as const;

export default function Privacy() {
  const [language, setLanguage] = useState<SiteLanguage>(getPreferredLanguage);
  const t = policyCopy[language];
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = t.dir; }, [language, t.dir]);
  const changeLanguage = (next: SiteLanguage) => { setLanguage(next); savePreferredLanguage(next); };
  return (
    <div className="dark-app" dir={t.dir}>
      <header className="dark-header"><a className="dark-brand" href={import.meta.env.BASE_URL} aria-label="GGUF Finder"><span className="dark-logo">↓</span><span><strong>GGUF</strong> Finder</span></a><div className="dark-header-tools"><span className="dark-header-note">{t.header}</span><LanguageSwitcher language={language} onChange={changeLanguage} /></div></header>
      <main className="dark-policy"><a className="dark-back" href={import.meta.env.BASE_URL}>{t.back}</a><p className="dark-eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="dark-policy-lead">{t.lead}</p><div className="dark-policy-note">{t.note}</div>{t.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</main>
    </div>
  );
}
